// <auto-generated />
using System;
using Abarrotes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abarrotes.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030205315_AddEstadoTipoPagoToCompras")]
    partial class AddEstadoTipoPagoToCompras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Abarrotes.Api.Models.Boleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("NumeroBoleta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_boleta");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_boletas");

                    b.HasIndex("NumeroBoleta")
                        .IsUnique()
                        .HasDatabaseName("ix_boletas_numero_boleta");

                    b.HasIndex("VentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_boletas_venta_id");

                    b.ToTable("boletas", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("DniRuc")
                        .HasColumnType("text")
                        .HasColumnName("dni_ruc");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AfectaInventario")
                        .HasColumnType("boolean")
                        .HasColumnName("afecta_inventario");

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean")
                        .HasColumnName("anulada");

                    b.Property<bool>("AplicaIgv")
                        .HasColumnType("boolean")
                        .HasColumnName("aplica_igv");

                    b.Property<string>("ComprobanteTipo")
                        .HasColumnType("text")
                        .HasColumnName("comprobante_tipo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Igv")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("igv");

                    b.Property<string>("NroComprobante")
                        .HasColumnType("text")
                        .HasColumnName("nro_comprobante");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("TipoPago")
                        .HasColumnType("text")
                        .HasColumnName("tipo_pago");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_compras");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_compras_proveedor_id");

                    b.ToTable("compras", "public");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.CompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<int>("CompraId")
                        .HasColumnType("integer")
                        .HasColumnName("compra_id");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_compras_detalle");

                    b.HasIndex("CompraId")
                        .HasDatabaseName("ix_compras_detalle_compra_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_compras_detalle_producto_id");

                    b.ToTable("compras_detalle", "public");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.ConsumoLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_consumos_lote");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_consumos_lote_lote_id");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("ix_consumos_lote_venta_id");

                    b.ToTable("consumos_lote", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_detalleventas");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_detalleventas_producto_id");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("ix_detalleventas_venta_id");

                    b.ToTable("detalleventas", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.EstadoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_estados_pago");

                    b.ToTable("estados_pago", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "pagado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "pendiente"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "anulado"
                        });
                });

            modelBuilder.Entity("Abarrotes.Api.Models.EstadoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_estadoproducto");

                    b.ToTable("estadoproducto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "inactivo"
                        });
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_factura");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_facturas");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("ix_facturas_numero_factura");

                    b.HasIndex("VentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_facturas_venta_id");

                    b.ToTable("facturas", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadActual")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad_actual");

                    b.Property<decimal>("CantidadInicial")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad_inicial");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_lotes");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_lotes_producto_id");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_lotes_proveedor_id");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_metodopago");

                    b.ToTable("metodopago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "yape"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "tarjeta"
                        });
                });

            modelBuilder.Entity("Abarrotes.Api.Models.NotaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.HasKey("Id")
                        .HasName("pk_notas_pedido");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_notas_pedido_cliente_id");

                    b.ToTable("notas_pedido", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EstadoProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_producto_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("StockReal")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("stock_real");

                    b.Property<string>("TipoMedida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_medida");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("ix_productos_codigo_barras");

                    b.HasIndex("EstadoProductoId")
                        .HasDatabaseName("ix_productos_estado_producto_id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ruc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_activo");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_utc");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("usuario_login");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_usuario_login");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ComprobanteNumero")
                        .HasColumnType("text")
                        .HasColumnName("comprobante_numero");

                    b.Property<int?>("EstadoPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_pago_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("TipoComprobante")
                        .HasColumnType("text")
                        .HasColumnName("tipo_comprobante");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_ventas_cliente_id");

                    b.HasIndex("EstadoPagoId")
                        .HasDatabaseName("ix_ventas_estado_pago_id");

                    b.HasIndex("MetodoPagoId")
                        .HasDatabaseName("ix_ventas_metodo_pago_id");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.VentaRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_venta_requests");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_venta_requests_key");

                    b.ToTable("venta_requests", (string)null);
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Boleta", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Venta", "Venta")
                        .WithOne("Boleta")
                        .HasForeignKey("Abarrotes.Api.Models.Boleta", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_boletas_ventas_venta_id");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Compra", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_proveedores_proveedor_id");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.CompraDetalle", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compras_detalle_compras_compra_id");

                    b.HasOne("Abarrotes.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_detalle_productos_producto_id");

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.ConsumoLote", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_lote_lotes_lote_id");

                    b.HasOne("Abarrotes.Api.Models.Venta", "Venta")
                        .WithMany("ConsumosLote")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_lote_ventas_venta_id");

                    b.Navigation("Lote");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.DetalleVenta", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Producto", "Producto")
                        .WithMany("Detalleventa")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalleventas_productos_producto_id");

                    b.HasOne("Abarrotes.Api.Models.Venta", "Venta")
                        .WithMany("Detalleventa")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalleventas_ventas_venta_id");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Factura", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Venta", "Venta")
                        .WithOne("Factura")
                        .HasForeignKey("Abarrotes.Api.Models.Factura", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_facturas_ventas_venta_id");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Lote", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_productos_producto_id");

                    b.HasOne("Abarrotes.Api.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("fk_lotes_proveedores_proveedor_id");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.NotaPedido", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Cliente", "Cliente")
                        .WithMany("Notaspedidos")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_notas_pedido_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Producto", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.HasOne("Abarrotes.Api.Models.EstadoProducto", "EstadoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("EstadoProductoId")
                        .HasConstraintName("fk_productos_estadoproducto_estado_producto_id");

                    b.Navigation("Categoria");

                    b.Navigation("EstadoProducto");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Venta", b =>
                {
                    b.HasOne("Abarrotes.Api.Models.Cliente", "Cliente")
                        .WithMany("Venta")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_ventas_clientes_cliente_id");

                    b.HasOne("Abarrotes.Api.Models.EstadoPago", "EstadoPago")
                        .WithMany("Venta")
                        .HasForeignKey("EstadoPagoId")
                        .HasConstraintName("fk_ventas_estados_pago_estado_pago_id");

                    b.HasOne("Abarrotes.Api.Models.MetodoPago", "MetodoPago")
                        .WithMany("Ventas")
                        .HasForeignKey("MetodoPagoId")
                        .HasConstraintName("fk_ventas_metodopago_metodo_pago_id");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoPago");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Cliente", b =>
                {
                    b.Navigation("Notaspedidos");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.EstadoPago", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.EstadoProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.MetodoPago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Producto", b =>
                {
                    b.Navigation("Detalleventa");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Abarrotes.Api.Models.Venta", b =>
                {
                    b.Navigation("Boleta");

                    b.Navigation("ConsumosLote");

                    b.Navigation("Detalleventa");

                    b.Navigation("Factura");
                });
#pragma warning restore 612, 618
        }
    }
}
